# Generated by Django 4.0.5 on 2022-10-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fathers Name'),
        ),
    ]
