# Generated by Django 4.0.5 on 2022-11-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester',
            field=models.IntegerField(verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='semesterinstance',
            name='elective',
            field=models.ManyToManyField(blank=True, null=True, related_name='elective_semester_instance', to='subject.subject'),
        ),
    ]
