# Generated by Django 4.0.5 on 2022-11-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='Credits'),
        ),
    ]
