# Generated by Django 4.0.5 on 2022-11-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_is_elective'),
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='credit',
        ),
        migrations.AddField(
            model_name='semesterinstance',
            name='credit',
            field=models.IntegerField(default=0, verbose_name='Credits'),
        ),
        migrations.AddField(
            model_name='semesterinstance',
            name='elective',
            field=models.ManyToManyField(related_name='elective_semester_instance', to='subject.subject'),
        ),
    ]
