# Generated by Django 4.0.5 on 2022-09-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Appearing'), ('P', 'Passed'), ('R', 'Reappear')], max_length=1, null=True),
        ),
    ]
