# Generated by Django 4.0.5 on 2022-11-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0002_remove_semester_credit_semesterinstance_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterinstance',
            name='credit',
        ),
    ]
