# Generated by Django 4.0.5 on 2022-11-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0002_alter_semester_credit'),
        ('semester', '0003_remove_semesterinstance_credit'),
    ]

    operations = [
    ]
