# Generated by Django 4.0.5 on 2022-11-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_elective',
            field=models.BooleanField(default=False, verbose_name='Is Elective'),
        ),
    ]
